---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/restaurants":
    get:
      summary: list restaurants
      tags:
        - Restaurants
      responses:
        '200':
          description: successful
    post:
      summary: create restaurant
      tags:
        - Restaurants
      responses:
        '200':
          description: successful
          
  "/api/v1/restaurants/{slug}":
    parameters:
    - name: slug
      in: path
      description: slug
      required: true
      schema:
        type: string
    get:
      summary: show restaurant
      tags:
        - Restaurants
      responses:
        '200':
          description: successful
    patch:
      summary: update restaurant
      tags:
        - Restaurants
      responses:
        '200':
          description: successful
    put:
      summary: update restaurant
      tags:
        - Restaurants
      responses:
        '200':
          description: successful
    delete:
      summary: delete restaurant
      tags:
        - Restaurants
      responses:
        '200':
          description: successful
  "/api/v1/reviews":
    post:
      summary: create review
      tags:
        - Reviews
      requestBody:   
        content:
          application/json:
            schema:
              type: object
              properties:
                 user:
                  required: true
                  type: string
                 comment:
                  required: true
                  type: string
                 score:
                  required: true
                  type: integer
                 restaurant_id:
                  required: true
                  type: integer
            example: '{"user": "user_test","comment": "The best food","score": 5,"restaurant_id": 1}'
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
